layout_spectrum: 1
description: primeira parte da trilogia das assassinas
name: adormecida
title: adormecida
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
navigation:
  - id: 6699c384-eae5-4713-aca6-23ad9ef3a168
    name: contato
    type: content
typography_spectrum: 0
color:
  brandStrength: 0.7932331
  lightness: 0
  saturation: 0.6854637
  rhythmicContrast: 0.7481203
  brandColors:
    - '#1D011C'
    - '#1EFEFE'
    - '#1DCFDB'
    - '#1B5699'
    - '#2792B7'
